%% Partial Decomposition of Granger Causality from VAR parameters

% Am,Su: VAR parameters (theoretical or estimated)
% is: indexes of sources (in a row vector)
% it: index of target (scalar)
% PID: struct with all info about PID (generated by hop_createMobiusN.m)
% Fs: sampling frequency
% nfft: number of frequency bins

function out=hop_pdgc(Am,Su,is,it,PID,Fs,nfft)

N=PID.Ns;%number of sources (target is assumed the last)
M=N+1;%total number of processes
Mv=ones(1,M);
Mob=PID.M;
ac=PID.ac'; %antichains
act=PID.act'; %textual antichains
cg=PID.cg; %coarse graining
L=length(ac); %number of antichains

%%% equivalent ISS model
[A,C,K,~] = hop_ar2iss(Am); % Eq. (26)

%% Computation of redundant GC functions over the antichains
%single antichains as numerical vector
convfact{1}=1; convfact{2}=[10 1]'; convfact{3}=[100 10 1]'; convfact{4}=[1000 100 10 1]'; %(max 4 sources)
acs=nan*ones(L,1);
for i=1:L
    if ~iscell(ac{i})
        acs(i)=ac{i}*convfact{length(ac{i})};
    end
end

% 1) compute spectral GCs from single (vector) source to target
rgc=nan*ones(L,nfft); %spectral redundant GC, ISSBarnett-based
for i=1:L
    if ~iscell(ac{i})
        i1=is(ac{i}); i2=it;
        rgc(i,:) = hop_sgc(A,C,K,Su,i1,i2,nfft); %here I keep GC   
    end
end
% 2) complete with spectral GCs from multiple (vector) sources to target (REDUNDANCY FUNCTION)
for i=1:L
    if iscell(ac{i})
        mirtmp=nan*ones(length(ac{i}),nfft); gctmp=mirtmp;
        for ill=1:length(ac{i})
            acstmp=ac{i}{ill}*convfact{length(ac{i}{ill})};
            gctmp(ill,:)=rgc(acstmp==acs,:);
        end
        rgc(i,:)=min(gctmp); %PIRD principle
    end
end

% atomic GC, obtained from redundant GC via Mobius inversion
agc=Mob'*rgc;

% coarse graining
cggc=zeros(N+2,nfft); %coarse-grained spectral GC (N unique, then synergistic, last redundant)
for i=1:L
    for iu=1:N
        if strcmp(cg(i,:),['U' int2str(iu)])
            cggc(iu,:)=cggc(iu,:)+agc(i,:);
        end
    end
    if strcmp(cg(i,:),'Sy')
        cggc(N+1,:)=cggc(N+1,:)+agc(i,:);
    end
    if strcmp(cg(i,:),'Rd')
        cggc(N+2,:)=cggc(N+2,:)+agc(i,:);
    end
end
for iu=1:N
    cglab(iu,:)=strcat('U',int2str(is(iu)));
end
cglab(N+1,:)='Sy';
cglab(N+2,:)='Rd';

% time domain
rGC=sum(rgc,2)./nfft; %segue act
aGC=sum(agc,2)./nfft; %segue act
cgGC=sum(cggc,2)./nfft; %segue cg


%% output
out.rgc=rgc; out.rGC=rGC; % causal GC redundancy function (frequency, TIME)
out.agc=agc; out.aGC=aGC; % causal GC atom information function (frequency, TIME)
out.cggc=cggc; out.cgGC=cgGC; % coarse GC grained atoms (frequency, TIME)

out.act=act; %antichains (ordering for rMIR, aMIR)
out.cg=cg; % coarse graining labels (for each atom)
out.cglab=cglab; %coarse graining (ordering for cgMIR)
out.freq = (0:nfft-1)*(Fs/(2*nfft)); % frequency axis
