%% State Space PIRD from VAR parameters

% Am,Su: VAR parameters (theoretical or estimated)
% is: indexes of sources (in a row vector)
% it: index of target (scalar)
% PID: struct with all info about PID (generated by hop_createMobiusN.m)
% Fs: sampling frequency
% nfft: number of frequency bins

function out=hop_sspird(Am,Su,is,it,PID,Fs,nfft)

N=PID.Ns;%number of sources (target is assumed the last)
M=N+1;%total number of processes
Mv=ones(1,M);
Mob=PID.M;
ac=PID.ac'; %antichains
act=PID.act'; %textual antichains
cg=PID.cg; %coarse graining
L=length(ac); %number of antichains

%%% equivalent ISS model
[A,C,K,~] = hop_ar2iss(Am); % Eq. (26)

%% Computation of redundant MIR functions over the antichains
%single antichains as numerical vector
convfact{1}=1; convfact{2}=[10 1]'; convfact{3}=[100 10 1]'; convfact{4}=[1000 100 10 1]'; %(max 4 sources)
acs=nan*ones(L,1);
for i=1:L
    if ~iscell(ac{i})
        acs(i)=ac{i}*convfact{length(ac{i})};
    end
end

% 1) compute spectral MIRs from single (vector) source to target
rmir=nan*ones(L,nfft); %spectral redundancy rate (nfft x L matrix, each in a row)
rte=nan*ones(L,nfft); %spectral causal redundancy rate, OIR-based
for i=1:L
    if ~iscell(ac{i})
        i1=is(ac{i}); i2=it;
        ret=hop_mir(A,C,K,Su,Mv,i1,i2,Fs,nfft);    
        rmir(i,:)=ret.t12'; 
        rte(i,:)=ret.t1_2'; 
    end
end
% 2) complete with spectral MIRs from multiple (vector) sources to target (REDUNDANCY FUNCTION)
for i=1:L
    if iscell(ac{i})
        mirtmp=nan*ones(length(ac{i}),nfft); tetmp=mirtmp;
        for ill=1:length(ac{i})
            acstmp=ac{i}{ill}*convfact{length(ac{i}{ill})};
            mirtmp(ill,:)=rmir(acstmp==acs,:);
            tetmp(ill,:)=rte(acstmp==acs,:);
        end
        rmir(i,:)=min(mirtmp); %PIRD principle
        rte(i,:)=min(tetmp); %PIRD principle
    end
end

% atomic MIR, obtained from redundant GC via Mobius inversion
amir=Mob'*rmir;
ate=Mob'*rte;

% coarse graining
cgmir=zeros(N+2,nfft); %coarse-grained spectral MIR (N unique, then synergistic, last redundant)
cgte=zeros(N+2,nfft); %coarse-grained spectral TE (N unique, then synergistic, last redundant)
for i=1:L
    for iu=1:N
        if strcmp(cg(i,:),['U' int2str(iu)])
            cgmir(iu,:)=cgmir(iu,:)+amir(i,:);
            cgte(iu,:)=cgte(iu,:)+ate(i,:);
        end
    end
    if strcmp(cg(i,:),'Sy')
        cgmir(N+1,:)=cgmir(N+1,:)+amir(i,:);
        cgte(N+1,:)=cgte(N+1,:)+ate(i,:);
    end
    if strcmp(cg(i,:),'Rd')
        cgmir(N+2,:)=cgmir(N+2,:)+amir(i,:);
        cgte(N+2,:)=cgte(N+2,:)+ate(i,:);
    end
end
for iu=1:N
    cglab(iu,:)=strcat('U',int2str(is(iu)));
end
cglab(N+1,:)='Sy';
cglab(N+2,:)='Rd';

% time domain
rMIR=sum(rmir,2)./nfft; %segue act
aMIR=sum(amir,2)./nfft; %segue act
cgMIR=sum(cgmir,2)./nfft; %segue cg

rTE=sum(rte,2)./nfft; %segue act
aTE=sum(ate,2)./nfft; %segue act
cgTE=sum(cgte,2)./nfft; %segue cg

%% output
out.rmir=rmir; out.rMIR=rMIR; % redundancy function (frequency, TIME)
out.amir=amir; out.aMIR=aMIR; % atom information function (frequency, TIME)
out.cgmir=cgmir; out.cgMIR=cgMIR; % coarse grained atoms (frequency, TIME)

out.rte=rte; out.rTE=rTE; % causal redundancy function (frequency, TIME)
out.ate=ate; out.aTE=aTE; % causal atom information function (frequency, TIME)
out.cgte=cgte; out.cgTE=cgTE; % coarse grained atoms (frequency, TIME)

out.act=act; %antichains (ordering for rMIR, aMIR)
out.cg=cg; % coarse graining labels (for each atom)
out.cglab=cglab; %coarse graining (ordering for cgMIR)
out.freq = (0:nfft-1)*(Fs/(2*nfft)); % frequency axis


